- components/package/AspetRatio/Demo.vue
- components/package/AspetRatio/Showcase.vue
- content/docs/primitives/2.components/1.label.md
- content/docs/primitives/2.components/2.aspet-ratio.md
- package.json
- pnpm-lock.yaml
> feat: Aspect Ratio

- components/docs/SideNavBar.vue
- pages/docs.vue
Closes #21 horizontal scroll
Fix navbar aspect on tablet
> fix: horizontal scroll

- components/package/toggle/Demo.vue
- components/package/toggle/Showcase.vue
- content/docs/primitives/2.components/toggle.md
- package.json
- pnpm-lock.yaml
> feat: toggle

- components/app/ComponentCard.vue
- components/content/PrimitivesShow.vue
> feat: improve component cards design

- pages/index.vue
going to ignore the template this time :)
you have antfu's sponser page, i replaced it with yours thats all :)
hard to get sponsers if your site is pointing to someone else's page
> fix: sponser link

- content/primitives/0.index.md
Hi @productdevbook, I've discovered issues with two links within the documentation. As a result, I've submitted this PR for your review. Please take a look when you have a moment. Thanks!
> fix: some broken links in documentation

- components/app/CodeGroup.vue
- components/docs/DocsPageBottom.vue
> fix: doc styles

- components/app/CodeGroup.vue
- components/primitives/OkuAvatar/index.vue
- components/primitives/OkuCheckbox/index.vue
- components/primitives/OkuCollapsible/index.vue
- components/primitives/OkuLabel/index.vue
- components/primitives/OkuProgress/index.vue
- components/primitives/OkuSeparator/index.vue
- components/primitives/OkuToggle/index.vue
close #47 
**I changed component background and component designs.**
**design bug: change checkbox's borders when checkbox is on checked**
> feat: component designs change dark/light

- components/primitives/OkuTabs/radix.vue
> fix: radix-tabs

- content/primitives/1.introduction/2.nuxt.md
> chore: improve nuxt module docs

- components/primitives/OkuAccordion/index.vue
- components/primitives/OkuAccordion/radix.vue
- tailwind.config.ts
accordion components fixes. animations doesn't work. (i don't know why doesn't work).
also i added down arrows animate. (it works)
> fix: radix component looks originally anymore

- components/primitives/OkuCheckbox/radix.vue
> fix: radix checkbox bugs fixed

- components/primitives/OkuDialog/radix.vue
- components/primitives/OkuHoverCard/index.vue
- components/primitives/OkuPopover/radix.vue
> fix: some components bug fixes

- content/pergel/1.getting-started/1.index.md
- content/pergel/2.os/1.index.md
- content/pergel/2.os/2.programs/1.index.md
- content/pergel/2.os/2.programs/_dir.yml
- content/pergel/2.os/2.programs/curl.md
- package.json
- pages/pergel/[...slug].vue
- pnpm-lock.yaml
- renovate.json
> feat: pergel install

- content/pergel/1.getting-started/1.index.md
> chore: update pergel introduction

- content/pergel/2.os/2.programs/git.md
> feat: added git documentation

- content/pergel/2.os/2.programs/beekeeper-studio.md
> feat(beekeeper): added beekeeper-studio to pergel

- content/pergel/2.os/2.programs/docker-desktop.md
> feat: docker-desktop.md

- content/pergel/2.os/2.programs/beekeeper-studio.md
> feat: beekeeper-studio

- content/pergel/2.os/2.programs/snap.md
> feat: snap

- content/pergel/2.os/2.programs/pnpm.md
> feat: pnpm

- composables/contributors.ts
- nuxt.config.ts
- pages/index.vue
- pages/oku.vue
- server/data/contributor-names.json
Add maintainers and update contributors display
Update nuxt.config.ts to comment out nuxt-og-image module
Update index.vue to add maintainers section
Remove team section from oku.vue
Add new contributor Aybee5
> chore: update contributors and maintainers
